#!/bin/bash

branches=('bzmr1' 'bzmr2' 'congo')
bzmr1=('1' 'bzmr1' 'maint' 'brazos_maint' 'rel/brazos_maint')
bzmr2=('2' 'bzmr2' 'rel/bzmr2')
congo=('congo' 'trunk')

function run_git_push {
	local branchName=$1
	local comfirmPushing="yes"
	
	if [[ $2 = 'c' || $2 = 'current' || $2 = 'currentbranch' ]]; then
		
		if [[ $branchName = 'master' ]]; then
			echo -n "git push -u origin master? (yes/no):"
		else
			echo -n "git push origin $branchName:refs/for/$branchName? (yes/no):"
		fi
		read comfirmPushing
		
		if [[ $comfirmPushing = 'y' || $comfirmPushing = 'ye' ||  $comfirmPushing = 'yes' ]]; then
			comfirmPushing="yes"
		else 
			comfirmPushing='no'
		fi
	fi
		
	if [[ $comfirmPushing = "yes" ]]; then
		if [[ $branchName = 'master' ]]; then
			git push -u origin master
		else
			git push origin $branchName:refs/for/$branchName
		fi
	fi
}

function getCurrentBranch {
	git rev-parse --abbrev-ref HEAD
}

function findBranch {
	local branchNickName=$1
	local branchName='' 
	
	if [[ $1 = 'c' || $1 = 'current' || $1 = 'currentbranch' ]]; then
		branchName=$(getCurrentBranch)
	fi
	
	for (( i = 0; i < ${#branches[@]}; i++ )); do
		if [[ -n $branchName ]]; then
			break
		fi
		eval "branch=\${${branches[i]}[@]}"
		branch=($branch)
		branchLen=${#branch[@]}
		for (( j = 0; j < branchLen; j++ )); do
			if [[ $branchNickName = ${branch[j]} ]]; then
				branchName=${branch[branchLen-1]}
				break
			fi
		done
	done
	
	echo $branchName
}

function pushFn {
	local branchName=$(findBranch $1)
	while [[ -z $branchName ]]; do
		echo "Branch is not defined or an invalid branch is given."
		echo -n "Please enter branch name:"
		read branchName
		branchName=$(findBranch $branchName)
	done
	
	run_git_push $branchName $2
}

function nginxStartFn {
	myvar="$PWD"
	cd /usr/local/etc/nginx/
	nginx
	cd "$myvar"
}

function stashFn {
	local stashMsg=$@
	while [[ -z $stashMsg ]]; do
		echo -n "No stash message. Please add: "
		read stashMsg
	done
	echo git stash save "'$stashMsg'"
	git stash save "$stashMsg"
}

function commitFn {
	local commitMsg=$@
	while [[ -z $commitMsg ]]; do
		echo -n "No commit message. Please add: "
		read commitMsg
	done
	echo git commit -m "'$commitMsg'"
	git commit -m "$commitMsg"
}

case $1 in
	(addcommit)
		echo "Run git add and commit -m"
		git add -u
		commitFn ${@:2};;
	(commit)
		echo "Run git commit -m"
		commitFn ${@:2};;
	(nginx)
		echo "Start Nginx"
		nginxStartFn;;
	(push) 
		echo "git push to remote"
		branchName="$2"
		pushFn $branchName $2;;
	(stash)
		echo "Run git stash save"
		stashFn ${@:2};;
esac

